import Head from 'next/head';
import { Inter } from '@next/font/google';
import Header from './Header';
import Footer from './Footer';

interface LayoutProps {
	children: React.ReactNode;
}

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });

const Layout = ({ children }: LayoutProps) => {
	return (
		<>
			<Head>
				<title>Nextjs | Starter kit</title>
				<meta
					name='description'
					content='Generated by devsnow nextjs starter template'
				/>
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='https://devsnow.in/logo.png' />
			</Head>

			<div
				className={`${inter.className} --font-sans mx-auto grid min-h-screen max-w-6xl grid-rows-[auto_1fr_auto] px-4 py-6`}
			>
				<Header />
				<main className='center'>{children}</main>
				<Footer />
			</div>
		</>
	);
};

export default Layout;
